# Generated by Django 4.2.1 on 2023-05-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="cctv",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="listings",
            name="elevator",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="listings",
            name="furnished",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="listings",
            name="parking",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="listings",
            name="pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="listings",
            name="rental_frequency",
            field=models.CharField(
                blank=True,
                choices=[("Week", "Week"), ("Month", "Month"), ("Day", "Day")],
                max_length=20,
                null=True,
            ),
        ),
    ]
