# Generated by Django 4.2.1 on 2023-05-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_listings_cctv_alter_listings_elevator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="picture1",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="listings",
            name="rental_frequency",
            field=models.CharField(
                blank=True,
                choices=[("Day", "Day"), ("Week", "Week"), ("Month", "Month")],
                max_length=20,
                null=True,
            ),
        ),
    ]
