# Generated by Django 4.2.1 on 2023-05-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_listings_picture1_alter_listings_rental_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="picture2",
            field=models.ImageField(
                blank=True, null=True, upload_to="pictures/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="listings",
            name="picture3",
            field=models.ImageField(
                blank=True, null=True, upload_to="pictures/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="listings",
            name="picture4",
            field=models.ImageField(
                blank=True, null=True, upload_to="pictures/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="listings",
            name="picture5",
            field=models.ImageField(
                blank=True, null=True, upload_to="pictures/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="picture1",
            field=models.ImageField(
                blank=True, null=True, upload_to="pictures/%Y/%m/%d/"
            ),
        ),
    ]
