# Generated by Django 4.2.1 on 2023-05-14 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0004_listings_picture2_listings_picture3_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="listings", name="location",),
        migrations.AddField(
            model_name="listings",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listings",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listings",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="rental_frequency",
            field=models.CharField(
                blank=True,
                choices=[("Month", "Month"), ("Week", "Week"), ("Day", "Day")],
                max_length=20,
                null=True,
            ),
        ),
    ]
