# Generated by Django 4.2.1 on 2023-05-14 11:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_remove_listings_location_listings_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="listings", name="latitude",),
        migrations.RemoveField(model_name="listings", name="longitude",),
        migrations.RemoveField(model_name="listings", name="seller",),
        migrations.AddField(
            model_name="listings",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="rental_frequency",
            field=models.CharField(
                blank=True,
                choices=[("Day", "Day"), ("Month", "Month"), ("Week", "Week")],
                max_length=20,
                null=True,
            ),
        ),
    ]
