# Generated by Django 4.2.1 on 2023-05-20 11:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_alter_listings_rental_frequency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("University", "University"),
                            ("Hospital", "Hospital"),
                            ("Stadium", "Stadium"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="listings",
            name="rental_frequency",
            field=models.CharField(
                blank=True,
                choices=[("Week", "Week"), ("Month", "Month"), ("Day", "Day")],
                max_length=20,
                null=True,
            ),
        ),
    ]
